github: Oncorporation
patreon: Surn
custom: ["https://www.paypal.me/CharlesFettinger", "https://live.blockcypher.com/ltc/address/MGo4THJBpy4y2k7hh6BoKiq6J5p641ygUC/","https://www.blockchain.com/btc/address/3HAN6eVxv81URgj51wxeCd9eMhg3tvriro","https://etherscan.io/address/0x79a67203CeA7c99b97c65D2982C8f35A4b968414"]
